[pytest]
#pythonpath = core functions # specify import paths
#testpaths = core functions # specify testing folders
python_files = test_*.py
python_functions = test_*

# docs: https://docs.pytest.org/en/stable/reference/customize.html