# TY TYPE CHECKER SETTINGS                                      # config: https://docs.astral.sh/ty/

# [environment]
# root = ["core", "functions"]

[src]
exclude = ["**/archive/**"]

# [rules]

# ty checker may consider pylance "type: ignore" as unused
# unused-type-ignore-comment = "ignore"
